### ISSUE TITLE
Why not just use servlets?

### ISSUE THREAD

**Issue by zack6849** [hypereddie/TinyHttp#1]
Pardon me, but i couldn't think of another way to send this
Looking at your code, it looks an awful lot to the HttpServlet API for java EE stuff, wouldn't it be easier for you to use that and maybe abstract away from it, rather than write all this from scratch?

**Comment by ecp4224** [comment]
But where would be the fun in that :) ?

I haven't looked at servlets before this project, and always thought it was some complex framework. But after looking it up, I do have to agree, this does look alot like servlets.

Regardless, I do want to see this project through (I only have one other feature I want to add), since I already started it.
